name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4

    - name: Check Python version
      run: python --version

    - name: Install dependencies
      run: make install
      working-directory: GitHub/MLOps

    - name: Run lint
      run: make lint
      working-directory: GitHub/MLOps

    - name: Run test
      run: make test
      working-directory: GitHub/MLOps
